package constant

const (
	HUMAN_CS_ROLE_RECEPTIONIST = "RECEPTIONIST"
	HUMAN_CS_ROLE_CLEANING     = "CLEANING"
	HUMAN_CS_ROLE_SECURITY     = "SECURITY"
)

const (
	HUMAN_CS_STATUS_ACTIVE   = "ACTIVE"
	HUMAN_CS_STATUS_OUT      = "OUT"
	HUMAN_CS_STATUS_INACTIVE = "INACTIVE"
)
