package constant

const (
	JOURNAL_STATUS_CANCEL    = "CANCEL"
	JOURNAL_STATUS_BOOKED    = "BOOKED"
	JOURNAL_STATUS_PAYED     = "PAYED"
	JOURNAL_STATUS_WAIT_COME = "WAIT_COME"
	JOURNAL_STATUS_CHECKIN   = "CHECKIN"
	JOURNAL_STATUS_CHECKOUT  = "CHECKOUT"
)
